const environment = require('../../config/environment');
const db = require('../../database');
module.exports.tables = {
    CalendarioDisponibleMedico: {
        id: 'Id_calendariodisp',
        user: 'id_Usuario',
        doctor: 'Codigo_persona',
        direccion: 'Id_Direccion',
        fecha: 'Fecha',
        hora: 'Hora',
        diaDisponible: 'id_estado_dia',
        horaDisponible: 'id_estado_hora',
    },
    DetalleCitasMedicas: {
        id: 'Id_cita',
        doctorUser: 'id_Usuario',
        doctorInfo: 'Codigo_persona',
        direccionHospital: 'Codigo_ubicacion_hospital',
        calendarioDisponible: 'Id_calendariodisp',
        pacienteUser: 'id_Usuario_paciente',
        pacienteInfo: 'Codigo_persona_paciente',
        status: 'id_estado',
    },
    Especializaciones: {
        id: 'id_especializacion',
        descripcion: 'Descripcion_especializacion',
        status: 'id_estado_especializacion',
    },
    EspecializacionesMedico: {
        especializacion: 'id_especializacion',
        doctorInfo: 'Codigo_persona',
        doctorUser: 'id_Usuario',
    },
    MedicoDisponibilidad: {
        doctorInfo: 'Id_persona',
        doctorUser: 'id_Usuario',
        id: 'id_Sec',
        status: 'id_estado',
        lunes: 'Lunes',
        martes: 'Martes',
        miercoles: 'Miercoles',
        jueves: 'Jueves',
        viernes: 'Viernes',
        sabado: 'Sabado',
        domingo: 'Domingo',
        aperturaLunes: 'Lunes_hora_apertura',
        aperturaMartes: 'Martes_hora_apertura',
        aperturaMiercoles: 'Miercoles_hora_apertura',
        aperturaJueves: 'Jueves_hora_apertura',
        aperturaViernes: 'Viernes_hora_apertura',
        aperturaSabado: 'Sabado_hora_apertura',
        aperturaDomingo: 'Domingo_hora_apertura',
        cierreLunes: 'Lunes_hora_cierre',
        cierreMartes: 'Martes_hora_cierre',
        cierreMiercoles: 'Miercoles_hora_cierre',
        cierreJueves: 'Jueves_hora_cierre',
        cierreViernes: 'Viernes_hora_cierre',
        cierreSabado: 'Sabado_hora_cierre',
        cierreDomingo: 'Domingo_hora_cierre',
    },
    PerfilMedico: {
        doctorInfo: 'Codigo_persona',
        doctorUser: 'id_Usuario',
        experiencia: 'Expericia_medico',
        honorarios: 'Honorarios_consulta',
        status: 'id_estado_medico',
    },
    ServiciosMedico: {
        id: 'id_servicios',
        doctorInfo: 'Codigo_persona',
        doctorUser: 'id_Usuario',
        descripcion: 'descripcion_servicios',
        status: 'id_estado_servicio',
    },
}

const Doctor = module.exports
